#old version
#version: 2.1
#
#orbs:
#  android: circleci/android@1.0.3
#  sonarcloud: sonarsource/sonarcloud@1.0.2
#
#jobs:
#  build:
#    executor: android/android
#
#    steps:
#      - checkout
#      - sonarcloud/scan
#      - run:
#          command: ./gradlew build
#workflows:
#  my-workflow:
#    jobs:
#      - build:
#          context: sonarcloud
#  test:
#    jobs:
#      # This job uses the Android machine image by default
#      - android/run-ui-tests:
#          # Use pre-steps and post-steps if necessary
#          # to execute custom steps before and afer any of the built-in steps
#          system-image: system-images;android-29;default;x86
#          disable-animations: true
version: '2.1'
orbs:
  android: circleci/android@2.0
jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-29;default;x86
workflows:
  test:
    jobs:
      - test
